# Generated by Django 6.1.1 on 2026-09-26 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0005_pedido_data_criacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='boleto',
            field=models.CharField(default='PIX', max_length=30),
        ),
    ]
