# Generated by Django 6.1 on 2026-10-05 21:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0005_pedido_data_criacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='boleto_arquivo',
            field=models.FileField(blank=True, null=True, upload_to='boletos/'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='data_criacao',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
