# Generated by Django 6.1 on 2026-10-05 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0006_pedido_boleto_arquivo_alter_pedido_data_criacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='forma_pagamento',
            field=models.CharField(choices=[('DINHEIRO', 'Dinheiro'), ('CONSIGNADO', 'Consignado'), ('PIX', 'Pix'), ('BOLETO', 'Boleto')], default='DINHEIRO', max_length=20),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='boleto',
            field=models.BooleanField(default=False),
        ),
    ]
