# Generated by Django 6.1.1 on 2026-09-26 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0006_alter_pedido_boleto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedido',
            old_name='boleto',
            new_name='forma_pagamento',
        ),
    ]
